/**
 * generate.c
 *
 * Computer Science 50
 * Problem Set 3
 *
 * Generates pseudorandom numbers in [0,LIMIT), one per line.
 *
 * Usage: generate n [s]
 *
 * where n is number of pseudorandom numbers to print
 * and s is an optional seed
 */
 
#define _XOPEN_SOURCE

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// constant
#define LIMIT 65536

int main(int argc, string argv[])
{
    // if there were not 2 and 3 command line arguments provided (where 1 is the program name)
    // print an error and returns 1 
    if (argc != 2 && argc != 3)
    {
        printf("Usage: generate n [s]\n");
        return 1;
    }

    // convert string to integer (since argv[] is an array of strings)
    int n = atoi(argv[1]);

    // If user provides the additional 3rd argument on the command line, it will be used as an argument for the
    // srand48() function so it then seeds drand48().

    if (argc == 3)
    {
        srand48((long int) atoi(argv[2]));  // uses argv[2] argument to seed the srand48() function
    }
    else
    {
        srand48((long int) time(NULL));    // uses the clock to to seed the srand48() function, time always 
    }                                      // changes so it will always create a different number.

    // prints the loop of random numbers generated by drand48(). Since drand46() it's of 'double' data type
    // it outputs a number over the interval [0.0, 1.0), multiplying it by the LIMIT will need to be done
    // to create a larger number.
    // Finally, we convert the 'double' to an integer by casting it with an (int) on its left side.
    for (int i = 0; i < n; i++)
    {
        printf("%i\n", (int) (drand48() * LIMIT));
    }

    // success
    return 0;
}